import { Work } from './types/work';

export const JOB_OFFERS: Work[] = [
  {
    id: 1,
    brand : "DODO Pizza",
    iconImageUrl: require('../assets/images/DODOLOGO.jpg'),
    postImageUrl : require('../assets/images/dodoWaiter.webp'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 2,
    brand : "Burger King",
    iconImageUrl: require('../assets/images/burgerking.png'),
    postImageUrl : require('../assets/images/burgerkingwaiter.jpg'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 3,
    brand : "DODO Pizza",
    iconImageUrl: require('../assets/images/dodopizzab.png'),
    postImageUrl : require('../assets/images/dodoWaiter.webp'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 4,
    brand : "Vkusno i Tochka",
    iconImageUrl: require('../assets/images/vkousnaitochka.jpeg'),
    postImageUrl : require('../assets/images/vkousnawaiter.jpg'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 5,
    brand : "DODO Pizza",
    iconImageUrl: require('../assets/images/dodopizzab.png'),
    postImageUrl : require('../assets/images/dodoWaiter.webp'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 6,
    brand : "DODO Pizza",
    iconImageUrl: require('../assets/images/dodopizzab.png'),
    postImageUrl : require('../assets/images/dodoWaiter.webp'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 7,
    brand : "DODO Pizza",
    iconImageUrl: require('../assets/images/dodopizzab.png'),
    postImageUrl : require('../assets/images/dodoWaiter.webp'),
    position: 'Официант',
    address : "Санкт-Петербург",
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 200,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      categoryImageUrl: require('../assets/images/waiter.jpeg'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
];