import { Work } from './types/work';

export const JOB_OFFERS: Work[] = [
  {
    id: 1,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      imageUrl1: require('../assets/images/waiter.jpeg'),

      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 2,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 3,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 4,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 5,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 6,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 7,
    brand: 'DoDO',
    imagesUrl: require('../assets/images/dodopizzab.png'),
    position: 'Waiter',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Waiter',
    category: {
      name: 'Fast Food',
      imageUrl: require('../assets/images/dodopizzab.png'),
      description: 'Jobs related to Fast Food And Restauration',
    },
    maxQuantityOfWorkers: 5,
  },
];