import { Work } from './types/work';

export const JOB_OFFERS: Work[] = [
  {
    id: 1,
    brand: 'Apple',
    imagesUrl: require('../assets/images/mac-book-1.jpg'),
    position: 'Software Engineer',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 50,
    description: 'Join our team as a Software Engineer working on cutting-edge technologies.',
    category: {
      name: 'Technology',
      imageUrl: require('../assets/images/mac-book-1.jpg'),
      description: 'Jobs related to technology and software development.',
    },
    maxQuantityOfWorkers: 5,
  },
  {
    id: 5,
    brand: 'Dell',
    imagesUrl: require('../assets/images/dell-1.jpg'),
    position: 'Hardware Technician',
    date: new Date('2024-07-01'),
    time: 35,
    hourlyPayment: 45,
    description: 'Assist in the maintenance and repair of Dell hardware products.',
    category: {
      name: 'Technology',
      imageUrl: require('../assets/images/mac-book-1.jpg'),
      description: 'Jobs related to technology and software development.',
    },
    maxQuantityOfWorkers: 7,
  },
  {
    id: 2,
    brand: 'Apple',
    imagesUrl: require('../assets/images/i-phone-1.jpg'),
    position: 'Mobile App Developer',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 55,
    description: 'Develop and maintain mobile applications for iOS devices.',
    category: {
      name: 'Technology',
      imageUrl: require('../assets/images/i-phone-1.jpg'),
      description: 'Jobs related to technology and software development.',
    },
    maxQuantityOfWorkers: 10,
  },
  {
    id: 6,
    brand: 'Samsung',
    imagesUrl: require('../assets/images/samsung-1.jpg'),
    position: 'Android Developer',
    date: new Date('2024-07-01'),
    time: 38,
    hourlyPayment: 50,
    description: 'Create and optimize Android applications for Samsung devices.',
    category: {
      name: 'Technology',
      imageUrl: require('../assets/images/i-phone-1.jpg'),
      description: 'Jobs related to technology and software development.',
    },
    maxQuantityOfWorkers: 12,
  },
  {
    id: 3,
    brand: 'Sony',
    imagesUrl: require('../assets/images/head-set-1.jpg'),
    position: 'Audio Engineer',
    date: new Date('2024-07-01'),
    time: 35,
    hourlyPayment: 40,
    description: 'Work on audio engineering projects for Sony headsets.',
    category: {
      name: 'Technology',
      imageUrl: require('../assets/images/head-set-1.jpg'),
      description: 'Jobs related to technology and software development.',
    },
    maxQuantityOfWorkers: 15,
  },
  {
    id: 4,
    brand: 'Sony',
    imagesUrl: require('../assets/images/ps-5-1.jpg'),
    position: 'Game Developer',
    date: new Date('2024-07-01'),
    time: 40,
    hourlyPayment: 60,
    description: 'Develop games for the PlayStation 5 platform.',
    category: {
      name: 'Gaming',
      imageUrl: require('../assets/images/ps-5-1.jpg'),
      description: 'Jobs related to game development and gaming industry.',
    },
    maxQuantityOfWorkers: 3,
  },
  {
    id: 7,
    brand: 'Nintendo',
    imagesUrl: require('../assets/images/nintendo-switch-1.jpg'),
    position: 'Game Tester',
    date: new Date('2024-07-01'),
    time: 30,
    hourlyPayment: 30,
    description: 'Test and provide feedback on Nintendo Switch games.',
    category: {
      name: 'Gaming',
      imageUrl: require('../assets/images/ps-5-1.jpg'),
      description: 'Jobs related to game development and gaming industry.',
    },
    maxQuantityOfWorkers: 8,
  },
];